version: '3'

services:
  front:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
