default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
 <<: *default
 database: development

test:
 <<: *default
 database: production

production:
 <<: *default
 database: <%= ENV["POSTGRES_DB"] %>
